### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/geoAssembler#2]
I've created both a `circle` branch ([builds](https://circleci.com/gh/European-XFEL/geoAssembler/tree/circleci)) and a `travis` branch ([builds](https://travis-ci.org/European-XFEL/geoAssembler/builds)), but neither is working at the moment. We probably only need one of them to work, but it's not as easy as I expected.

Has anyone set up CI for another project using PyQt recently? I've looked at Spyder for inspiration, but that's doing all sorts of things which I hope we don't need to.

**Comment by tmichela** [comment]
Looks like a similar issue KaraboFAI had in the past with GUI tests, Denivy solved it there: https://in.xfel.eu/gitlab/dataAnalysis/karaboFAI/merge_requests/60

Basically some dependencies are missing that pyQt5 needs to run.

**Comment by takluyver** [comment]
The Travis branch is now working, but only by duplicating all of the requirements in the Travis config file. I guess the pyqt5 installed by conda is invisible to pip, so if you `pip install .` it installs PyQt5 from PyPI, which I think is part of the problem.

**Comment by takluyver** [comment]
Thanks to the hint from Denivy's change, I've now got the tests *running* on Circle, but three of them are giving me an error:

```
RuntimeError: wrapped C/C++ object of type QPlainTextEdit has been deleted
```

**Comment by takluyver** [comment]
And I was eventually able to get the tests working by turning off the log messages going into a dialog - see #3.
