### ISSUE TITLE
Optimise centre using azimuthal integration

### ISSUE THREAD

**Issue by takluyver** [European-XFEL/geoAssembler#8]
@RobertRosca wrote some code which optimises the centre of the geometry using an image containing rings, by maximising a peak in the azimuthal integration of the image.

Although this automatic procedure is quite different from the manual geometry tools currently in this repo, I think it would fit in best here (i.e. geoAssembler as a collection of tools for creating and refining geometry definitions).

We should ensure it's still easy to visualise the results of this process, so people can notice if the optimisation goes off in the wrong direction.

**Comment by RobertRosca** [comment]
Done in pull request [here](https://github.com/European-XFEL/geoAssembler/pull/10)

WIP as it isn't completely finished, but the core functionality is there.

**Comment by takluyver** [comment]
Done in PR #22
